service: quiz-app-backend

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-1
  httpApi:
    cors: true
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:DescribeTable
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

package:
  patterns:
    - '!node_modules/**'
    - '!README.md'
    - '!package.json'
    - '!package-lock.json'
    - '!requirements.txt'

functions:

  create:
    handler: src/create.create
    timeout: 5
    memorySize: 128
    events:
      - httpApi:
          path: /quizzes
          method: POST

  get:
    handler: src/get.get
    timeout: 5
    memorySize: 128
    events:
      - httpApi:
          path: /quizzes/{device_id}
          method: GET

resources:
  Resources:
    QuizzesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: device_id
            AttributeType: S
        KeySchema:
          - AttributeName: device_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
  